# Generated by Django 5.1 on 2024-08-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('body', models.TextField()),
                ('year_of_birth', models.IntegerField()),
                ('year_of_death', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nationality', models.CharField(max_length=75)),
                ('banner', models.ImageField(default='default.png', upload_to='heroes_banner/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='heroes_images/')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='heroes.hero')),
            ],
        ),
    ]
