# Generated by Django 5.1 on 2024-09-14 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_hero_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='date_selected',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
