# Generated by Django 5.1 on 2024-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0008_alter_hero_year_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
